did some tasks

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,22 +1,33 @@
 #!/usr/bin/env bash
-# install nginx with hello world at /
+#install ngix and have a file that returns the string "Hello World  inside
 
-sudo apt-get update -qq && \
-sudo apt-get install nginx -y
-
-#sudo systemctl start nginx
-sudo service nginx start
-# sudo nginx start
-
-# allow nginx on firewall
-sudo ufw allow 'Nginx HTTP'
-
-# ownership stuff
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
-
-# === hello world content ===
-sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
-
-sudo nginx -s reload
-
+sudo apt-get update -y && \
+sudo apt-get install -y nginx
+if [ $? -eq 0 ]
+then
+    echo -e \
+"http {
+    root /var/www/school;
+    index index.html;
+    server {
+        listen 80;
+        location \ {
+        }
+    }
+}
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/school
+    echo "Hello World!" > \
+	/var/www/school/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
+else
+    echo "Could not install nginx"
+    exit 1
+fi
+exit 0
